version: '3.0'
services:

  postgresql:
    #image:  postgres:9.6
    image: kartoza/postgis:9.6-2.4
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: Welcome123
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db1
    command: >
      -c work_mem=256MB
      -c maintenance_work_mem=256MB
      -c max_wal_size=1GB
    ports:
      - "5435:5432"
    #volumes:
       # Persist the data between container invocations
       # - ./logs:/logs
  web:
    build: .
    command: sh start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
